// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PipelineIntegrityAPI.Data;

#nullable disable

namespace PipelineIntegrityAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Inspection", b =>
                {
                    b.Property<Guid>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<int>("MaxDepthPct")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InspectionId");

                    b.HasIndex("SegmentId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Pipeline", b =>
                {
                    b.Property<Guid>("PipelineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PipelineId");

                    b.ToTable("Pipelines");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.RiskScore", b =>
                {
                    b.Property<Guid>("RiskScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<Guid>("SegmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RiskScoreId");

                    b.HasIndex("SegmentId")
                        .IsUnique();

                    b.ToTable("RiskScores");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Segment", b =>
                {
                    b.Property<Guid>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EndLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("EndLng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("LengthKm")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("PipelineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("StartLat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("StartLng")
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("SegmentId");

                    b.HasIndex("PipelineId");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Inspection", b =>
                {
                    b.HasOne("PipelineIntegrityAPI.Models.Segment", "Segment")
                        .WithMany("Inspections")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.RiskScore", b =>
                {
                    b.HasOne("PipelineIntegrityAPI.Models.Segment", "Segment")
                        .WithOne("RiskScore")
                        .HasForeignKey("PipelineIntegrityAPI.Models.RiskScore", "SegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Segment", b =>
                {
                    b.HasOne("PipelineIntegrityAPI.Models.Pipeline", "Pipeline")
                        .WithMany("Segments")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Pipeline", b =>
                {
                    b.Navigation("Segments");
                });

            modelBuilder.Entity("PipelineIntegrityAPI.Models.Segment", b =>
                {
                    b.Navigation("Inspections");

                    b.Navigation("RiskScore");
                });
#pragma warning restore 612, 618
        }
    }
}
